services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    command: --global-response-templating
    volumes:
      - ./wiremock:/home/wiremock

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: